---
openapi: 3.0.3
info:
  title: Order Management service API
  description: Demo for Order Management service
  contact:
    name: IBM Garage Solution Engineering
    url: http://https://ibm-cloud-architecture.github.io/refarch-eda/
    email: noone@superemail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
tags:
- name: eda
  description: IBM Event Driven Architecture
paths:
  /api/v1/orders:
    get:
      tags:
      - Order Resource
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderDTO'
    put:
      tags:
      - Order Resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderDTO'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDTO'
    post:
      tags:
      - Order Resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderDTO'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDTO'
  /api/v1/version:
    get:
      tags:
      - Version Resource
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    Address:
      type: object
      properties:
        street:
          type: string
        city:
          type: string
        country:
          type: string
        state:
          type: string
        zipcode:
          type: string
    OrderDTO:
      type: object
      properties:
        orderID:
          type: string
        customerID:
          type: string
        productID:
          type: string
        quantity:
          format: int32
          type: integer
        destinationAddress:
          $ref: '#/components/schemas/Address'
        creationDate:
          type: string

