apiVersion: v1
kind: ConfigMap
metadata:
  name: qs-order-mgr-cm
data:
  APP_VERSION: 0.0.1
  KAFKA_BOOTSTRAP_SERVERS: dev-kafka-bootstrap.smq-dev.svc:9093
  KAFKA_TOPIC_NAME: qs-orders
  ES_APICURIO_URL: https://dev-ibm-es-ac-reg-external-smq-dev.cp4i-es-mq-1e3af63cfd19e855098d645120e18baf-0000.us-south.containers.appdomain.cloud
  

  